[flake8]
max-line-length = 79
max-complexity = 10


stages:
  model_building:
    cmd: python src/model/model_building.py
    deps:
    - src/model/model_building.py
    - data/processed/train.csv
    - models/scaler.pkl
    params:
    - model_building.parameters.learning_rate
    - model_building.parameters.max_depth
    - model_building.parameters.n_estimators
    - model_building.parameters.subsample
    outs:
    - models/model.pkl

  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - src/model/model_evaluation.py
    - models/model.pkl
    - data/processed/test.csv
    outs:
    - reports/metrics.json
    - reports/experiment_info.json

  model_registration:
    cmd: python src/model/register_model.py
    deps:
    - src/model/register_model.py
    - reports/metrics.json
    - reports/experiment_info.json
    - models/model.pkl
    params:
    - register_model.MODEL_NAME
    - register_model.ACCEPTANCE_CRITERIA.min_r2
    - register_model.ACCEPTANCE_CRITERIA.max_rmse
