name: CI-CD MLOps Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Upgrade pip
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # 4. Cache pip dependencies
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 5. Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 6. Show project structure (debug)
      - name: List project files
        run: |
          pwd
          ls -R
      
      # 7. Run DVC pipeline
      - name: Run DVC pipeline
        env:
          DAGSHUB_TOKEN_HEALTH: ${{ secrets.DAGSHUB_TOKEN_HEALTH }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          dvc repro

      # 8. Run model test
      - name: Run model tests
        env:          
          DAGSHUB_TOKEN_HEALTH: ${{ secrets.DAGSHUB_TOKEN_HEALTH }}
        run: |
          python -m unittest tests/test_model.py

      # 9. Run flask app test
      - name: Run Flask app tests
        env:          
          DAGSHUB_TOKEN_HEALTH: ${{ secrets.DAGSHUB_TOKEN_HEALTH }}
        run: |
          python -m unittest tests/test_flask_app.py

      
      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          region: ${{ secrets.AWS_REGION }}

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${GITHUB_SHA}
          docker build -t $IMAGE_TAG .

      - name: Push Docker image to ECR
        run: |
          docker push $IMAGE_TAG
